### ISSUE TITLE
testing: write a test to validate that custom attributes can flow through the display configuration

### ISSUE THREAD

**Issue by mattkae** [canonical/ubuntu-frame#184]
Validate that custom attributes can be provided in the display configuration. This
  was first encountered in [#172](https://github.com/canonical/ubuntu-frame/issues/172). To
  test:
  1. Start a Mir compositor with the `--display-config static=$FILENAME` flag
  2. In the configuration, have a custom attribute, e.g. `snap-name` in the following example:
     ```yaml
     # ...
      HDMI-A-4:
        state: enabled
        mode: 2560x1440@60.0
        position: [2560, 0]
        orientation: normal
        scale: 1
        group: 0
        snap-name: mir-kiosk-neverputt
     ```
  3. Check the logs of your compositor. On `ubuntu-frame` you can do:
     ```sh
     snap logs ubuntu-frame -n 50
     ```
  4. Validate that you see your custom attribute when the display is logged
