### ISSUE TITLE
Apps going fullscreen despite custom size

### ISSUE THREAD

**Issue by Saviq** [canonical/ubuntu-frame#221]
Steps:
- configure Frame to place mir-kiosk-neverputt custom
  https://mir-server.io/docs/how-to-configure-ubuntu-frame-for-multiple-outputs#heading--custom-client-placement
   ```yaml
   layouts:
     default:
       cards:
       - card-id: 0

       applications:
       - snap-name: mir-kiosk-neverputt
         position: [640, 0]
         size: [640, 512]
   ```
- start frame and neverputt

Expected:
- placed at the configured layout

Current:
- decorations shown at the current layout (#220)
- app shown in fullscreen size, positioned according to layout

![Image](https://github.com/user-attachments/assets/703256cd-0f4a-4127-93d0-aec2bbdbe72e)
