### ISSUE TITLE
Launcher shown when launcher=false

### ISSUE THREAD

**Issue by robinelvin** [canonical/ubuntu-frame#229]
I have set `launcher=false` in the ubuntu-frame config but it is still being shown. This is a dual-display setup so that may be a factor.

```shell
$ snap list
Name                  Version                 Rev    Tracking       Publisher       Notes
core20                20250429                2582   latest/stable  canonical✓      base
core22                20250408                1963   latest/stable  canonical✓      base
core24                20250504                988    latest/stable  canonical✓      base
docker                27.5.1                  3064   latest/stable  canonical✓      -
media-player          0.1                     x1     -              -               -
mesa-2404             24.2.8                  495    latest/stable  canonical✓      -
mesa-core20           21.2.6                  165    latest/stable  canonical✓      -
mesa-core22           23.2.1                  368    latest/stable  canonical✓      -
network-manager       1.46.0-4                962    24/stable      canonical✓      -
pc                    24-0.1                  x1     -              -               gadget
pc-kernel             6.8.0-60.63             2465   24/stable      canonical✓      kernel
snapd                 2.68.4                  24505  latest/stable  canonical✓      snapd
ubuntu-frame          211-mir2.20.1           12495  24/stable      canonical✓      -
ubuntu-frame-osk      97-sb1.43.1-1           1064   24/stable      canonical✓      -
ubuntu-frame-vnc      84-wayvnc0.7.2-1build2  643    24/stable      canonical✓      -
usbutils-snap         014                     2      latest/stable  drcoccodrillus  -
vpn-setup             0.1                     x1     -              -               devmode
wpe-webkit-mir-kiosk  2.38.5                  100    latest/stable  glancr          -
```

```shell
$ snap get ubuntu-frame launcher
false
```

![Image](https://github.com/user-attachments/assets/0cad1d3e-be97-4f46-9872-6ec558b256e4)

**Comment by Saviq** [comment]
@robinelvin hey, can you please post the output of `snap services ubuntu-frame`?

I suspect things got out of sync. Simplest fix is `snap stop --disable ubuntu-frame.launcher`, but `snap set ubuntu-frame launcher=true; snap set ubuntu-frame launcher=false` should result in the same.

**Comment by Saviq** [comment]
@robinelvin if you can give a reproducer and describe how you get in that situation, we'd be interested!

**Comment by robinelvin** [comment]
We build a custom Ubuntu Core x86_64 system from our model assertion which includes the snap packages listed previously. After the system has booted, expanded the filesystem, and the user assertion is applied from a USB stick an Ansible playbook is run to perform the configuration steps. Here is the relevant part of the playbook followed by the handlers which get triggered. You can see the commands that are run in each handler and they run in the order defined.

```yaml
- name: Ubuntu Frame
  block:
    - name: Copy Ubuntu Frame Config
      ansible.builtin.template:
        src: uf-config.j2
        dest: RVM5Py/uf-config
        mode: "0666"
      notify:
        - Configure Ubuntu Frame
        - Hide Mouse Pointer
        - Set Video Layout
        - Configure Kiosk
        - Start Kiosk
        - Start Kiosk OSK

    - name: Read Ubuntu Frame Config
      ansible.builtin.slurp:
        src: RVM5Py/uf-config
      register: display_config
```

```yaml
- name: Configure Ubuntu Frame
  ansible.builtin.command:
    cmd: "snap set ubuntu-frame display='{{ display_config.content | b64decode | trim }}' launcher=false daemon=true"

- name: Hide Mouse Pointer
  ansible.builtin.command:
    cmd: 'snap set ubuntu-frame config="cursor=null"'

- name: Set Video Layout
  ansible.builtin.command:
    cmd: "snap set ubuntu-frame display-layout=side_by_side"

- name: Configure Kiosk
  ansible.builtin.command:
    cmd: "snap set wpe-webkit-mir-kiosk url=http://localhost:8000 bg-color=white devmode={{ rvm_web_inspector }}"

- name: Start Kiosk
  ansible.builtin.command:
    cmd: "snap start --enable ubuntu-frame"

- name: Start Kiosk OSK
  ansible.builtin.command:
    cmd: "snap start --enable ubuntu-frame-osk"
```
